### ISSUE TITLE
CC_CONFIGURATION_V4:   bulk_report_send()

### ISSUE THREAD

**Issue by N2641D** [stevew817/AMS2ZWAVE#1]
Hi Steven,
This is an excellent project - congratulations!!! Also thank you for your answer about "CC_CONFIGURATION / CC_CONFIGURATION_V4" at the Z-Wave Wireless Forum.

I also have started to write a command class for CONFIGURATION two weeks ago and then recognized your work. When doing a few tests with the SiLabs ZWave Controller, I found that CONFIGURATION_BULK_GET_V4 and CONFIGURATION_BULK_SET_V4 (handshake=1) did not send any data back to the controller.

Having done a few changes (see // WP change) it now seems to work.

Best Regards,

Wilfried

-------------------------------------------

#include "SizeOf.h"                // WP change

// Start sending bulk report. Returns false if another bulk report is still in
// progress.
static bool bulk_report_send( uint16_t param, size_t num_param, bool handshake, TRANSMIT_OPTIONS_TYPE_SINGLE_EX *pTxOptionsEx) {
  // Figure out the size of the first parameter
  size_t param_size = 0;
  for( size_t i = 0; i < sizeof(parameter_table) / sizeof(parameter_table[0]); i++ ) {
    if( parameter_table[i].param_nbr == param ) {
      param_size = parameter_table[i].param_size;
      break;
    }
  }

  if( param_size == 0 ) {
      // parameter offset points to non-existing parameter
      // SDS13781 does not say what action we should take in this case,
      // except that 'The Configuration Bulk Report Command MUST be
      // returned in response to this command'. This implies we should
      // choose some arbitrary length and run with it?
      param_size = 1;
  }

  // For each parameter within the range, check whether they correspond to their
  // default.
  bool all_default = true;
  for( size_t i = 0; i < sizeof(parameter_table) / sizeof(parameter_table[0]); i++ ) {
    if( parameter_table[i].param_nbr >= param &&
        parameter_table[i].param_nbr < (param + num_param) ) {
      switch( param_size ) {
        case 1:
          if( *((uint8_t*)(parameter_table[i].param)) != parameter_table[i].param_default.u8 )
            all_default = false;
          break;
        case 2:
          if( *((uint16_t*)(parameter_table[i].param)) != parameter_table[i].param_default.u16 )
            all_default = false;
          break;
        case 4:
          if( *((uint32_t*)(parameter_table[i].param)) != parameter_table[i].param_default.u32)
            all_default = false;
          break;
        default:
          break;
      }
      break;
    }
  }

  uint8_t size_handshake_byte = (param_size & 0x7) | (handshake ? (1 << 6) : 0) | (all_default ? (1 << 7) : 0);
  size_t num_reports          = (num_param * param_size) / max_chars_per_report;
  if( (num_param * param_size) % max_chars_per_report != 0 ) num_reports++;

  if(handshake) {
    // Handshake response requires answering in a single packet
    num_reports = 1;
  }

  if(num_reports > 1) {
    // Need to start multipart report, check there's none in progress yet
    if( bulk_report_in_progress.in_progress ) return false;

    // Set up new multipart report
    bulk_report_in_progress.in_progress           = true;
    bulk_report_in_progress.pkg_options           = *pTxOptionsEx;
    bulk_report_in_progress.param_nbr             = param;
    bulk_report_in_progress.total_num_parameters  = num_param;
    bulk_report_in_progress.num_packets_remaining = num_reports;
    bulk_report_in_progress.size_handshake_byte   = size_handshake_byte;

    bulk_report_progress_cb( 0 );
  }
  else {
    // We can send this report at once
    ZAF_TRANSPORT_TX_BUFFER  TxBuf;
    ZW_APPLICATION_TX_BUFFER *pTxBuf = &(TxBuf.appTxBuf);
    memset((uint8_t*)pTxBuf, 0, sizeof(ZW_APPLICATION_TX_BUFFER) );

    // Name and info reports look identical besides their command ID.
    pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.cmdClass           = COMMAND_CLASS_CONFIGURATION_V4;
    pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.cmd                = CONFIGURATION_BULK_REPORT_V4;
    pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.parameterOffset1   = (param>>8) & 0xFF;  // WP change
    pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.parameterOffset2   = param & 0xFF;       // WP change
    pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.numberOfParameters = num_param;          // WP change
    pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.reportsToFollow    = 0;
    pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.properties1        = param_size;         // WP change

    uint8_t* param_buffer = (uint8_t*)&pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.variantgroup1;

    // Copy all parameters for this packet. It is assumed parameter existence and size
    // has been validated before ending up in this CB.
    for( size_t i = 0; i < num_param; i++ ) {
      // For each parameter number, find it in the table and copy its value
      bool param_found = false;
      for (size_t j=0; j<sizeof_array(parameter_table); j++) {                              // WP change
        if( parameter_table[j].param_nbr == param + i ) {                                   // WP change
          switch(param_size) {
            case 1:
              param_buffer[i * param_size] = *((uint8_t*)(parameter_table[j].param));
              break;
            case 2:
              param_buffer[i * param_size + 0] = *((uint16_t*)(parameter_table[j].param)) >> 8;
              param_buffer[i * param_size + 1] = *((uint16_t*)(parameter_table[j].param)) & 0xFF;
              break;
            case 4:
              param_buffer[i * param_size + 0] = (*((uint32_t*)(parameter_table[j].param)) >> 24) & 0xFF;
              param_buffer[i * param_size + 1] = (*((uint32_t*)(parameter_table[j].param)) >> 16) & 0xFF;
              param_buffer[i * param_size + 2] = (*((uint32_t*)(parameter_table[j].param)) >>  8) & 0xFF;
              param_buffer[i * param_size + 3] = (*((uint32_t*)(parameter_table[j].param)) >>  0) & 0xFF;
              break;
            default:
              break;
          }
          param_found = true;
          break;
        }
      }

      // SDS13781: A sending node SHOULD set this field to 0 for non-existing parameters
      if( !param_found ) memset(&param_buffer[i * param_size], 0, param_size);
    }
    size_t report_size = (num_param * param_size) + offsetof(ZW_CONFIGURATION_BULK_REPORT_1BYTE_V4_FRAME, variantgroup1);

    // Send it
    if( EQUEUENOTIFYING_STATUS_SUCCESS != Transport_SendResponseEP((uint8_t *)pTxBuf, report_size, pTxOptionsEx, NULL) ) {  // WP change
        ; // Job failed
    }
  }

  return true;
}

**Comment by stevew817** [comment]
Thanks for the contribution, @N2641D! I'll try this tonight and pull it in.

**Comment by stevew817** [comment]
@N2641D I've applied your feedback and fixed some more for the case where a report needs to be split across multiple messages. Can you check it out (should be on master branch now) on your end and give a thumbs up or down?

**Comment by N2641D** [comment]
Hi Steven,

That was a really quick response. Thank you!

I have done a couple of tests and I think that there might be still some issues. I have created a test which contains 20 parameters 4bytes each. Their parameter offset is 1024…1043.

Unfortunately the SiLabs ZWave Controller’s log window has a bug to not wrap around the returned package data. I’m therefore unable to verify the returned package in detail (if the line gets too long).

Yesterday I forgot to highlight one change...

  // Copy all parameters for this packet. It is assumed parameter existence and size
  // has been validated before ending up in this CB.
  for( size_t i = 0; i < num_report_items; i++ ) {
    // For each parameter number, find it in the table and copy its value
    bool param_found = false;
    for( size_t j = 0; j < sizeof_array(parameter_table); j++ ) {
      if( parameter_table[j].param_nbr == this_pkt_param_start + i ) {
        param_found = true; 

… which makes sure that the value will not be identified as “non existing parameter” and of course not be reset to 0. That line is missing for n packages too.

When increasing the numbers of parameters to be returned everything looks almost fine up to 9 parameters (e.g. 1 parameter: (70 09) + 04 00 01 00 84 00 00 01 00). One thing I’m not sure is whether or not the “Default” bit should be set (0x84)?

When increasing the number of parameters to 10 the CONFIGURATION_BULK_GET looks still okay (70 08 04 00 0A). Your code decides to still go with one package and everything looks okay, however, although the call:

    // Send it
    DPRINTF("**** SEND IT\r\n");
    if( EQUEUENOTIFYING_STATUS_SUCCESS != Transport_SendResponseEP((uint8_t *)pTxBuf, report_size, pTxOptionsEx, NULL) ) {
      DPRINTF("**** JOB FAILED ****\r\n");
        ; // Job failed
    }

is executed without error, no data will be sent! I therefore guess that 10x4byte values do exceed the maximum number of bytes per report and "max_chars_per_report = 40” must be decreased.
When increasing the BULK_GET request to 11 parameters, the returned package (04 0A 01 00 84 00 00 00 00) is no longer okay. The parameter offset 1024 showed "(04 0A)”.

In order to get the report right, please find enclosed my proposal for some changes of bulk_report_progress_cb() (lines changed: // WP change”).

As far as I could see (issue with log window) the returned reports seem to be okay. One last question… is the split between 1-block and n-blocks software required? I would think that n-blocks would also work for 1-block? … but I’m not an Z-Wave expert :-) 

Have a great evening!

Best,

Wilfried


—————————————————————————————


static const size_t max_chars_per_report = 39;  // WP change


static void bulk_report_progress_cb( uint8_t status ) {
  ZAF_TRANSPORT_TX_BUFFER  TxBuf;
  ZW_APPLICATION_TX_BUFFER *pTxBuf = &(TxBuf.appTxBuf);
  memset((uint8_t*)pTxBuf, 0, sizeof(ZW_APPLICATION_TX_BUFFER));

  size_t num_report_items;
  size_t item_size         = bulk_report_in_progress.size_handshake_byte & 0x7;
  uint16_t items_per_block = max_chars_per_report/item_size; // WP change

  size_t total_packets = ((bulk_report_in_progress.total_num_parameters*item_size-1)/(items_per_block*item_size)) + 1; // WP change
  if( bulk_report_in_progress.num_packets_remaining > 0 ) {
    num_report_items = max_chars_per_report / item_size;
  }
  else {
      num_report_items = bulk_report_in_progress.total_num_parameters - (total_packets-1)*items_per_block;  // WP change
  }

  size_t this_pkt_offset = total_packets - bulk_report_in_progress.num_packets_remaining - 1;
  uint16_t this_pkt_param_start = bulk_report_in_progress.param_nbr + (this_pkt_offset * (max_chars_per_report / item_size));

  // Name and info reports look identical besides their command ID.
  pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.cmdClass           = COMMAND_CLASS_CONFIGURATION_V4;
  pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.cmd                = CONFIGURATION_BULK_REPORT_V4;
  pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.parameterOffset1   = (this_pkt_param_start >> 8) & 0xFF;
  pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.parameterOffset2   = this_pkt_param_start & 0xFF;
  pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.numberOfParameters = num_report_items;
  pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.reportsToFollow    = bulk_report_in_progress.num_packets_remaining;
  pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.properties1        = bulk_report_in_progress.size_handshake_byte;

  uint8_t* param_buffer = (uint8_t*)&pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.variantgroup1;

  // Copy all parameters for this packet. It is assumed parameter existence and size
  // has been validated before ending up in this CB.
  for( size_t i = 0; i < num_report_items; i++ ) {
    // For each parameter number, find it in the table and copy its value
    bool param_found = false;
    for( size_t j = 0; j < sizeof_array(parameter_table); j++ ) {
      if( parameter_table[j].param_nbr == this_pkt_param_start + i ) {
        param_found = true;     // WP change
        switch(item_size) {
          case 1:
            param_buffer[i * item_size] = *((uint8_t*)(parameter_table[j].param));
            break;
          case 2:
            param_buffer[i * item_size + 0] = *((uint16_t*)(parameter_table[j].param)) >> 8;
            param_buffer[i * item_size + 1] = *((uint16_t*)(parameter_table[j].param)) & 0xFF;
            break;
          case 4:
            param_buffer[i * item_size + 0] = (*((uint32_t*)(parameter_table[j].param)) >> 24) & 0xFF;
            param_buffer[i * item_size + 1] = (*((uint32_t*)(parameter_table[j].param)) >> 16) & 0xFF;
            param_buffer[i * item_size + 2] = (*((uint32_t*)(parameter_table[j].param)) >>  8) & 0xFF;
            param_buffer[i * item_size + 3] = (*((uint32_t*)(parameter_table[j].param)) >>  0) & 0xFF;
            break;
          default:
            break;
        }
        break;
      }
    }

    // SDS13781: A sending node SHOULD set this field to 0 for non-existing parameters
    if( !param_found ) {
      memset(&param_buffer[i * item_size], 0, item_size);
    }
  }

  size_t report_size = (num_report_items * item_size) + offsetof(ZW_CONFIGURATION_BULK_REPORT_1BYTE_V4_FRAME, variantgroup1);

  if( bulk_report_in_progress.num_packets_remaining > 0 ) {
    if( EQUEUENOTIFYING_STATUS_SUCCESS != Transport_SendResponseEP((uint8_t *)pTxBuf, report_size, &bulk_report_in_progress.pkg_options, bulk_report_progress_cb) ) {
      // Failed to queue the packet somehow, meaning we won't get a
      // new callback. Give up on this transmission.
      bulk_report_in_progress.in_progress = false;
    }
    bulk_report_in_progress.num_packets_remaining--;
  }
  else {
    if( EQUEUENOTIFYING_STATUS_SUCCESS != Transport_SendResponseEP((uint8_t *)pTxBuf, report_size, &bulk_report_in_progress.pkg_options, NULL) ) {
      ;
    }
    // Full string has been transmitted
    bulk_report_in_progress.in_progress = false;
  }
}

// Start sending bulk report. Returns false if another bulk report is still in
// progress.
static bool bulk_report_send( uint16_t param, size_t num_param, bool handshake, TRANSMIT_OPTIONS_TYPE_SINGLE_EX *pTxOptionsEx) {
  // Figure out the size of the first parameter
  size_t param_size = 0;
  for( size_t i = 0; i < sizeof_array(parameter_table); i++ ) {
    if( parameter_table[i].param_nbr == param ) {
      param_size = parameter_table[i].param_size;
      break;
    }
  }

  if( param_size == 0 ) {
      // parameter offset points to non-existing parameter
      // SDS13781 does not say what action we should take in this case,
      // except that 'The Configuration Bulk Report Command MUST be
      // returned in response to this command'. This implies we should
      // choose some arbitrary length and run with it?
      param_size = 1;
  }

  // For each parameter within the range, check whether they correspond to their
  // default.
  bool all_default = true;
  for( size_t i = 0; i < sizeof_array(parameter_table); i++ ) {
    if( parameter_table[i].param_nbr >= param && parameter_table[i].param_nbr < (param + num_param) ) {
      switch( param_size ) {
        case 1:
          if( *((uint8_t*)(parameter_table[i].param)) != parameter_table[i].param_default.u8 )
            all_default = false;
          break;
        case 2:
          if( *((uint16_t*)(parameter_table[i].param)) != parameter_table[i].param_default.u16 )
            all_default = false;
          break;
        case 4:
          if( *((uint32_t*)(parameter_table[i].param)) != parameter_table[i].param_default.u32)
            all_default = false;
          break;
        default:
          break;
      }
      break;
    }
  }

  uint8_t size_handshake_byte = (param_size & 0x7) | (handshake ? (1 << 6) : 0) | (all_default ? (1 << 7) : 0);

  //size_t num_reports = (num_param * param_size) / max_chars_per_report;
  //if( (num_param * param_size) % max_chars_per_report != 0 ) num_reports++;
  size_t num_reports = ((num_param*param_size-1)/(uint16_t)((max_chars_per_report/param_size)*param_size))+1; // WP change

  if( handshake ) {
    // Handshake response requires answering in a single packet
    num_reports = 1;
  }

  if( num_reports > 1 ) {
    // Need to start multipart report, check there's none in progress yet
    if( bulk_report_in_progress.in_progress ) return false;

    // Set up new multipart report
    bulk_report_in_progress.in_progress           = true;
    bulk_report_in_progress.pkg_options           = *pTxOptionsEx;
    bulk_report_in_progress.param_nbr             = param;
    bulk_report_in_progress.total_num_parameters  = num_param;
    bulk_report_in_progress.num_packets_remaining = num_reports - 1;
    bulk_report_in_progress.size_handshake_byte   = size_handshake_byte;

    bulk_report_progress_cb( 0 );
  } else {
    // We can send this report at once
    ZAF_TRANSPORT_TX_BUFFER  TxBuf;
    ZW_APPLICATION_TX_BUFFER *pTxBuf = &(TxBuf.appTxBuf);
    memset((uint8_t*)pTxBuf, 0, sizeof(ZW_APPLICATION_TX_BUFFER) );

    // Name and info reports look identical besides their command ID.
    pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.cmdClass           = COMMAND_CLASS_CONFIGURATION_V4;
    pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.cmd                = CONFIGURATION_BULK_REPORT_V4;
    pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.parameterOffset1   = (param >> 8) & 0xFF;
    pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.parameterOffset2   =  param & 0xFF;
    pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.numberOfParameters = num_param;
    pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.reportsToFollow    = 0;
    pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.properties1        = size_handshake_byte;

    uint8_t* param_buffer = (uint8_t*)&pTxBuf->ZW_ConfigurationBulkReport1byteV4Frame.variantgroup1;

    // Copy all parameters for this packet. It is assumed parameter existence and size
    // has been validated before ending up in this CB.
    for( size_t i = 0; i < num_param; i++ ) {
      // For each parameter number, find it in the table and copy its value
      bool param_found = false;
      for( size_t j = 0; j < sizeof_array(parameter_table); j++ ) {

        if( parameter_table[j].param_nbr == param + i ) {
          param_found = true;     // WP change
          switch(param_size) {
            case 1:
              param_buffer[i * param_size] = *((uint8_t*)(parameter_table[j].param));
              break;
            case 2:
              param_buffer[i * param_size + 0] = *((uint16_t*)(parameter_table[j].param)) >> 8;
              param_buffer[i * param_size + 1] = *((uint16_t*)(parameter_table[j].param)) & 0xFF;
              break;
            case 4:
              param_buffer[i * param_size + 0] = (*((uint32_t*)(parameter_table[j].param)) >> 24) & 0xFF;
              param_buffer[i * param_size + 1] = (*((uint32_t*)(parameter_table[j].param)) >> 16) & 0xFF;
              param_buffer[i * param_size + 2] = (*((uint32_t*)(parameter_table[j].param)) >>  8) & 0xFF;
              param_buffer[i * param_size + 3] = (*((uint32_t*)(parameter_table[j].param)) >>  0) & 0xFF;
              break;
            default:
              break;
          }
          break;
        }
      }

      // SDS13781: A sending node SHOULD set this field to 0 for non-existing parameters
      if( !param_found ) {
        memset(&param_buffer[i * param_size], 0, param_size);
      }
    }

    size_t report_size = (num_param * param_size) + offsetof(ZW_CONFIGURATION_BULK_REPORT_1BYTE_V4_FRAME, variantgroup1);

    // Send it
    if( EQUEUENOTIFYING_STATUS_SUCCESS != Transport_SendResponseEP((uint8_t *)pTxBuf, report_size, pTxOptionsEx, NULL) ) {
        ; // Job failed
    }
  }

  return true;
}

**Comment by stevew817** [comment]
Damn. Okay, I'll have a much closer look.

**Comment by N2641D** [comment]
… I just did another quick test. I created 46 parameters (1 Byte each).  39 is the magic number we were looking for!

**Comment by stevew817** [comment]
>  One last question… is the split between 1-block and n-blocks software required? I would think that n-blocks would also work for 1-block? … but I’m not an Z-Wave expert :-)

Yes, it should work. I made the distinction between single-packet and multi-packet response handling for two reasons:
1. When a multi-packet response is in progress to one node, we can still send single-packet responses to other nodes which might be querying us simultaneously
2. When the handshake bit is set, the response is expected to fit into a single packet, since the set command fit in a single packet as well. Since I was unsure about the sizing of the packet, splitting up the logic allowed me to 'override' the sizing calculations in case of replying to a bulk set command :)

There's definitely room for collapsing that into one given some more thought, but I'm not sure it would be a priority at this point. I'm assuming the compiler is smart enough to alias the common bits of code between two static functions in the same compilation unit :)

Should probably start reporting 'node busy' to the requesting node when a bulk get fails due to another one already being in flight, though.

> Unfortunately the SiLabs ZWave Controller’s log window has a bug to not wrap around the returned package data. I’m therefore unable to verify the returned package in detail (if the line gets too long).

Yeah, I ran into that too. Fortunately, it's just bad UI design: if your screen resolution is large enough (or even better, if you have two screens), you can 'drag' the right side of the window to be larger, and you'll see a mark appear for widening the message view visible column width. Took me some time before I noticed that.

> please find enclosed my proposal for some changes 

Much appreciated! I pushed them through #3 onto master just now.
